### ISSUE TITLE
Interact with cat

### ISSUE THREAD

**Issue by gregorywood** [gregorywood/pushkinsprefers#1]
the idea is pushkins will be interactive

* a click/tap animates her and changes out the page background
* there's a sequence of animations as you continue to irritate (click/tap) her
* eventually she shows her bum and squirts wee at you and the background goes into a mad pixel psychedelic adventure

**Comment by joshuaswift** [comment]
#31 🐈

**Comment by gregorywood** [comment]
Redundant now the cat and the animations aren't in the same place
