### ISSUE TITLE
Change the link-hover randomiser a bit

### ISSUE THREAD

**Issue by gregorywood** [gregorywood/pushkinsprefers#6]
randomiser is working great! can we iterate on it a little?

can the randomised array be applied to each item, and not all of them? ie if there were 10 links on the page, the hover colours could go like this:

![image](https://user-images.githubusercontent.com/881722/49512127-ec61bd00-f884-11e8-96f9-c71afc34d319.png)

or like this:

![image](https://user-images.githubusercontent.com/881722/49512136-f1267100-f884-11e8-9066-7c3c8db3e240.png)

currently we are randomising and then applied the outcome to all items, I'd like to see if we can randomise for each. does that make sense?

**Comment by joshuaswift** [comment]
Makes perfect sense, should be a fairly quick iteration!

**Comment by joshuaswift** [comment]
@gregorywood this can be closed now I believe
