### ISSUE TITLE
Ability to use arrow keys for nav on the catalog

### ISSUE THREAD

**Issue by gregorywood** [gregorywood/pushkinsprefers#7]

**Comment by joshuaswift** [comment]
this looks to be harder than I initially thought to implement but [this](https://stackoverflow.com/questions/33790668/arrow-keys-navigation-through-li-no-jquery) looks to be an OK approach

**Comment by gregorywood** [comment]
hmm thinking about this further, it's hijacking default behaviour, which is bad for usability and accessibility

I was thinking of ways to make it more game-y but tab/shift-tab works just as well. happy to close this idea as redundant

**Comment by gregorywood** [comment]
void
